
export const ROOT_USER_LOGIN= "ROOT_USER_LOGIN";
export const ROOT_LOGIN_WATCHER= "ROOT_LOGIN_WATCHER";

export const ROOT_USER_LOGOUT ="ROOT_USER_LOGOUT";
export const LOGOUT_WATCHER = "LOGOUT_WATCHER";

export const ROOT_USER_PASSWORD_RESET_REQ = "ROOT_USER_PASSWORD_RESET_REQ";
export const ROOT_USER_PASSWORD_RESET_REQ_WATCHER = "ROOT_USER_PASSWORD_RESET_REQ_WATCHER";

export const ROOT_PASSWORD_RESET_WATCHER = "ROOT_PASSWORD_RESET_WATCHER";
export const ROOT_USER_PASSWORD_RESET = "ROOT_USER_PASSWORD_RESET";







export const PRACTICE_USER_LOGIN= "PRACTICE_USER_LOGIN";
export const PRACTICE_LOGIN_WATCHER= "PRACTICE_LOGIN_WATCHER";


export const PRACTICE_USER_LOGOUT ="PRACTICE_USER_LOGOUT";
export const PRACTICE_LOGOUT_WATCHER = "PRACTICE_LOGOUT_WATCHER";

export const PRACTICE_USER_PASSWORD_RESET_REQ = "PRACTICE_USER_PASSWORD_RESET_REQ";
export const PRACTICE_USER_PASSWORD_RESET_REQ_WATCHER = "PRACTICE_USER_PASSWORD_RESET_REQ_WATCHER";

export const PRACTICE_PASSWORD_RESET_WATCHER = "PRACTICE_PASSWORD_RESET_WATCHER";
export const PRACTICE_USER_PASSWORD_RESET = "PRACTICE_USER_PASSWORD_RESET";





















export const API_FAILED = "API_FAILED";





















export const IS_LOADING = "IS_LOADING";
export const LOADED = "LOADED";
export const LOAD_FAILED = "LOAD_FAILED";
